resolver: lts-16.24
packages:
- '.'

extra-deps:
- stylish-haskell-0.11.0.0
- hlint-2.1.26
- haskeline-0.8.1.0
- regex-posix-clib-2.7   # only for testing
- json-0.10

flags:
  haskeline:
    terminfo: false
  regex-posix:
      _regex-posix-clib: true